name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - requests=2.24.0
  - pyarrow
  - numpy = 1.24
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - git+https://github.com/mpatil1313/Project-Build-an-ML-Pipeline-Starter-7dec.git#egg=wandb-utils&subdirectory=components
